import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./styles/globals.css";
import NavBar from "@/components/shared/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dev Showcase",
  description: "Generated by create next app",
  icons: { icon: "/devShowcase-logo.ico" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} } h-full antialiased`}
    >
      <body className="mx-auto w-11/12">
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
